#
# Makefile for the fingerprint drivers.
#

obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208) += goodix/
obj-$(CONFIG_FINGERPRINT_FPC1020) += fpc/

subdir-ccflags-y := -finline-functions -ftree-vectorize -funroll-loops
