ccflags-y := -I$(src)/../../../../drivers/nvdimm/
ccflags-y += -I$(src)/../../../../drivers/acpi/nfit/

obj-y += nfit_test.o
obj-y += nfit_test_iomap.o

nfit_test-y := nfit.o
nfit_test_iomap-y := iomap.o
